spring:
  profiles:
    active: local
        
    ## datasource 설정
  datasource:
    hikari:
      rws:
        jdbc-url: url
        username: username
        password: password
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        # driver-class-name: org.mariadb.jdbc.Driver
        pool-name: default-r-pool
  devtools:
    livereload:
      enabled: true
    freemarker:
      cache: false
  jwt:
    secret: secret
# mybatis setting
mybatis:
      mapper-locations: mybatis/mapper/*.xml
      configuration:
        map-underscore-to-camel-case: true
        return-instance-for-empty-row: true
        
        
logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace
              
biz :
    post_url : https://teht.hometax.go.kr/wqAction.do?actionId=ATTABZAA001R08&screenId=UTEABAAA13&popupYn=false&realScreenId=
    xml_rows : <map id="ATTABZAA001R08"><pubcUserNo/><mobYn>N</mobYn><inqrTrgtClCd>1</inqrTrgtClCd><txprDscmNo>{CRN}</txprDscmNo><dongCode>86</dongCode><psbSearch>Y</psbSearch><map id="userReqInfoVO"/></map><nts<nts>nts>
              
