spring:
  profiles:
    active: local
        
    ## datasource 설정
  datasource:
    hikari:
      rws:
        jdbc-url: jdbc:log4jdbc:mysql://115.143.85.142:3307/rws?characterEncoding=UTF-8&serverTimezone=UTC
        username: rws
        password: rwsepdlxjqpdltm1!
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        # driver-class-name: org.mariadb.jdbc.Driver
        pool-name: default-r-pool
  devtools:
    livereload:
      enabled: true
    freemarker:
      cache: false
  jwt:
    secret: govlepel@$&
# mybatis setting
mybatis:
      mapper-locations: mybatis/mapper/*.xml
      configuration:
        map-underscore-to-camel-case: true
        return-instance-for-empty-row: true
        
        
logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace